#!/usr/bin/env bash
# generate-api-signatures.sh — Extracts public API signatures from teavm-react source
# and writes references/api-signatures.md.
#
# Usage: cd <repo-root> && ./skills/teavm-react/scripts/generate-api-signatures.sh
#
# Requirements: grep, sed, awk (standard Unix tools)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
CORE_SRC="$REPO_ROOT/teavm-react-core/src/main/java/ca/weblite/teavmreact"
KOTLIN_SRC="$REPO_ROOT/teavm-react-kotlin/src/main/kotlin/ca/weblite/teavmreact/kotlin"
OUTPUT="$REPO_ROOT/skills/teavm-react/references/api-signatures.md"

cat > "$OUTPUT" << 'HEADER'
# API Signatures Reference

> Read this file to find the exact class name, method name, and parameter types
> for any teavm-react API. This prevents hallucinating methods that don't exist.
> Grouped by package. Kotlin DSL functions are at the end.

HEADER

# ============================================================
# Java API — extract public/protected method and class declarations
# ============================================================

extract_java_package() {
    local pkg_path="$1"
    local pkg_name="$2"
    local pkg_dir="$CORE_SRC/$pkg_path"

    if [ ! -d "$pkg_dir" ]; then return; fi

    echo "## $pkg_name" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    for file in "$pkg_dir"/*.java; do
        [ -f "$file" ] || continue
        local classname
        classname=$(basename "$file" .java)

        echo "### $classname" >> "$OUTPUT"
        echo "" >> "$OUTPUT"

        # Extract class/interface declaration line
        grep -E '^\s*public\s+(abstract\s+|final\s+)?(class|interface|enum)\s+' "$file" \
            | sed 's/^\s*//' | head -1 \
            | while read -r line; do echo "    $line" >> "$OUTPUT"; done

        echo "" >> "$OUTPUT"

        # Extract public/protected method signatures (exclude private, native bridge helpers)
        grep -E '^\s*(public|protected)\s+' "$file" \
            | grep -v '^\s*\*' \
            | grep -v 'private' \
            | grep -v '^\s*//' \
            | grep -vE '^\s*(public|protected)\s+(abstract\s+|final\s+)?(class|interface|enum)\s+' \
            | sed 's/^\s*/- /' \
            | sed 's/ {$//' \
            | sed 's/;$//' \
            >> "$OUTPUT" 2>/dev/null || true

        echo "" >> "$OUTPUT"
    done
}

extract_java_package "core" "ca.weblite.teavmreact.core"
extract_java_package "hooks" "ca.weblite.teavmreact.hooks"
extract_java_package "events" "ca.weblite.teavmreact.events"
extract_java_package "html" "ca.weblite.teavmreact.html"
extract_java_package "component" "ca.weblite.teavmreact.component"

# ============================================================
# Kotlin DSL — extract top-level and extension functions
# ============================================================

echo "## ca.weblite.teavmreact.kotlin" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for file in "$KOTLIN_SRC"/*.kt; do
    [ -f "$file" ] || continue
    local_name=$(basename "$file" .kt)
    echo "### $local_name" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # Extract class declarations
    grep -E '^(open\s+|data\s+|sealed\s+|abstract\s+)?class\s+' "$file" \
        | sed 's/^\s*/- /' >> "$OUTPUT" 2>/dev/null || true

    # Extract top-level and extension functions
    grep -E '^fun\s+' "$file" \
        | sed 's/^\s*/- /' >> "$OUTPUT" 2>/dev/null || true

    # Extract extension functions (on ComponentScope, HtmlBuilder, Flow, etc.)
    grep -E '^fun\s+(ComponentScope|HtmlBuilder|Flow<)' "$file" \
        | sed 's/^\s*/- /' >> "$OUTPUT" 2>/dev/null || true

    echo "" >> "$OUTPUT"
done

echo "---" >> "$OUTPUT"
echo "*Generated by scripts/generate-api-signatures.sh*" >> "$OUTPUT"

echo "Generated: $OUTPUT"
